version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql-don-berriondo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'variedades-don-berriondo'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - berriondo-net

  # Servicio de la aplicación Spring Boot
  app:
    container_name: app-don-berriondo
    build: .
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/variedades-don-berriondo?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: '12345678'

      SECURITY_JWT_KEY_PRIVATE: 'CLAVEMUYSEGURA'
      SECURITY_JWT_USER_GENERATOR: 'VariedadesDonBerriondoApp'
    networks:
      - berriondo-net

# Definición de los volúmenes
volumes:
  db_data:

# Definición de las redes
networks:
  berriondo-net:
    driver: bridge
